### ISSUE TITLE
About how much memory is needed 

### ISSUE THREAD

**Issue by 17bcwu** [skjerns/AutoSleepScorer#13]
Hello, author.To run AutoSleepScorerDev How much memory do i need? My memory is 16G .Every time there is a memory overflow

**Comment by skjerns** [comment]
16GB is plenty.

Are you running on the GPU?
How much GPU memory do you have?
At which point do you experience the memory overflow?

**Comment by skjerns** [comment]
I'm closing this. Feel free to reopen once you can provide more details on your problem, such as the questions I asked. I'm not a fortune-teller, so I don't even know if this is a GPU or RAM problem, or if it appears during loading of data, during classification or whatsoever.

1. step: Please copy a full traceback of the problem
2. step: answer the questions above

**Comment by 17bcwu** [comment]
I'm sorry, my English is not very good. I didn't express it well. Your project is excellent. I sincerely apologize to you for making you angry. I'm trying to sort out the problems clearly, and Then I'll ask you for advice.

**Comment by skjerns** [comment]
No problem! I'm happy to help if you can supply me with the traceback of the error. This means the message that python prints once it's having a problem.

I've tested it and the memory intensive process is likely the creation of the sleepdata.pkl from the sleep-edfx database. You can run the script on the CPU machine and then copy the sleepdata.pkl that is created in the same folder as the script to the folder of the GPU machine.

Then the script will not recreate the database, but use the existing sleepdata.pkl, which will need approximately 2.7GB of RAM to load.
