### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by 17bcwu** [skjerns/AutoSleepScorer#14]
hello,I run the run_sample.py, but it occurs a error like thess:

  File "C:\Users\bc\Desktop\AutoSleepScorerDev-master\keras_utils.py", line 689, in cv
    train_data   = [data[j] for j in train_idx]

  File "C:\Users\bc\Desktop\AutoSleepScorerDev-master\keras_utils.py", line 689, in <listcomp>
    train_data   = [data[j] for j in train_idx]

IndexError: index 46139 is out of bounds for axis 0 with size 45242

the error occured when the model build the cv dataset, the train index is out of bound.

**Comment by skjerns** [comment]
Mhh this is strange. I'll see if I can look into this, but before Christmas I will likely not have time.
