### ISSUE TITLE
Cannot open 'cnn.hdf5'  'rnn.hdf5'

### ISSUE THREAD

**Issue by cjpark87** [skjerns/AutoSleepScorer#2]
I am trying to run the example code you posted in README.md. But, when loading the model hdf5 file, it shows an error.

File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

It seems like the model files are corrupted when I try to run "h5debug cnn.hdf5".

HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139994803136256:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file

Could you check the model files again?

FYI, I am running your code in Ubuntu 16.04 with python3

**Comment by skjerns** [comment]
I fixed the links. should work now. Re-clone to get the new links.
