### ISSUE TITLE
Questions about Scorer()&kerncloud

### ISSUE THREAD

**Issue by komdec** [skjerns/AutoSleepScorer#21]
Hello, skjerns
I'm Guo, a student in China, and I'm trying to reproduce this code, but I'm having some problems.
When I run the function **Scorer()** I need to download the model weights from the website "http://cloud.skjerns.de/index.php/s/X3iTwBrRy5qzEtg/download/cnn.hdf5", but the kerncloud website says " The document could not be found on the server. This share may have been deleted or expired." Did you change to another site?
My email is 2211849@s.hlju.edu.cn

**Comment by skjerns** [comment]
Ah yes, I changed my cloud setup. I updated the links - try reinstalling.

**Comment by komdec** [comment]
Thank you very much, I have run it successfully
