### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gsamyak30** [skjerns/AutoSleepScorer#24]
ok !! But I have installed the new version than where I should run the code with the old version of keras , tensorflow and h5py!! How could I install the older version !!
One more that the dropbox link that you have shared if I just click on that link it shows the files are deleted !! Does it affect the code !!
Secondly how will I get the hypnogram so either it will be downloaded or show directly after the successfull execution of code!!

**Comment by skjerns** [comment]
you can install it via `pip install keras=x.x.x`

just google this please, I cannot give basic Python support here. This is a develop version for people with programming/pthon knowledge, no end-user application.

**Comment by gsamyak30** [comment]
Thank You Simon
