### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by madhhir** [skjerns/AutoSleepScorer#25]
Hi Simon, I'm getting this error.

main.py", line 50, in <module>

    if os.path.isdir(path):

TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType

Could you please help in identifying the reason why the path is inaccessible?

**Comment by skjerns** [comment]
what did you use as an input argument? the path to the PSG/EDF file should be supplied using the first argument. if you don't supply it, you will get this error

**Comment by madhhir** [comment]
> what did you use as an input argument? the path to the PSG/EDF file should be supplied using the first argument. if you don't supply it, you will get this error

https://www.physionet.org/content/sleep-edfx/1.0.0/sleep-cassette/SC4001E0-PSG.edf
This path has been taken as per the code.

**Comment by skjerns** [comment]
yes, you need a local file path, no URL
