### ISSUE TITLE
comparision

### ISSUE THREAD

**Issue by gsamyak30** [skjerns/AutoSleepScorer#26]
Hi Simon

Just want to ask can I get the hypnogram image which contain both human and cnn+lstm as you have paste image in your introduction part just because as I am getting only edf file image

**Comment by skjerns** [comment]
I simply plot the hypnogram 1 in red and overlay the second one in blue. For this, of course, you need to have both hypnograms available.


have a look at https://github.com/skjerns/sleep-utils/blob/master/sleep_utils/plotting.py , there you find a function `plot_hypnogram` which should serve your purpose

**Comment by gsamyak30** [comment]
Hi Simon

But one doubt as how can we get the second hypnogram as in the code we have 
scorer.run() - This will give hypnogram image
tools.show_sample_hypnogram('sample-psg.groundtruth.csv', start=960, stop=1800) - But this cant generate the image then how we can generate the image of other

**Comment by gsamyak30** [comment]
Hi Simon
Just a basic question

if a edf file is in float then how we can convert into csv file

**Comment by skjerns** [comment]
sorry this has nothing to do with this project. this is a general python question better to be asked to an appropriate place like stackoverflow or your supervisor
