### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by gsamyak30** [skjerns/AutoSleepScorer#31]
Hi Simon

For Plotting a confusion matrix we require a square matrix but like how can we make a square matrix from the dataset as the data are in the csv format and they are very long entries data so do you apply any code for making matrix or you have just done mannualy or you have done in excel ?

**Comment by skjerns** [comment]
Please stop writing issues in this repository that are not related to the project itself. You can find out how to create a confusion matrix by googleing what a confusion matrix is and how you can create it. If you understand the theory behind it, it will be easy to create. Sorry for this frank answer, but I this is not the place to ask for things like this.
